This notebook apply a cleaning data procedure to ground based observations to be compared to modeled WRF-Chem surface pollutants over Delhi NCT.

## Data

Data downloaded from the CPCB portal and reformatted using format_CPCB_data.ypnb

## Import libraries

In [1]:
import pandas as pd
import numpy as np

## Load raw data

In [2]:
delhi= pd.read_csv('./cpcb_oct2019_formatted.csv')

In [3]:
delhi

,Unnamed: 0,pm25,pm10,no,no2,nox,nh3,so2,temp,rh,...,date_LT,year_LT,month_LT,day_LT,hour_LT,date_UTC,year_UTC,month_UTC,day_UTC,hour_UTC
0,0,54.5,113.0,5.25,38.78,24.90,15.40,11.58,NaN,89.85,...,2019-10-01 00:00:00,2019,10,1,0,2019-09-30 19:00:00,2019,9,30,19
1,1,44.5,85.0,5.20,37.50,24.20,15.18,11.12,NaN,91.93,...,2019-10-01 01:00:00,2019,10,1,1,2019-09-30 20:00:00,2019,9,30,20
2,2,40.5,76.0,3.35,31.40,19.40,19.60,13.25,NaN,93.20,...,2019-10-01 02:00:00,2019,10,1,2,2019-09-30 21:00:00,2019,9,30,21
3,3,43.5,81.5,3.45,32.67,20.23,17.62,11.97,NaN,94.05,...,2019-10-01 03:00:00,2019,10,1,3,2019-09-30 22:00:00,2019,9,30,22
4,4,51.5,89.0,3.40,32.57,20.07,18.38,12.57,NaN,94.30,...,2019-10-01 04:00:00,2019,10,1,4,2019-09-30 23:00:00,2019,9,30,23
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26070,29050,447.0,705.0,34.15,6.73,31.45,63.95,39.15,NaN,89.00,...,2019-10-31 20:00:00,2019,10,31,20,2019-10-31 15:00:00,2019,10,31,15
26071,29051,446.0,670.5,35.05,8.20,32.92,66.75,41.38,NaN,90.35,...,2019-10-31 21:00:00,2019,10,31,21,2019-10-31 16:00:00,2019,10,31,16
26072,29052,451.5,638.5,36.43,7.03,33.45,72.08,42.05,NaN,91.05,...,2019-10-31 22:00:00,2019,10,31,22,2019-10-31 17:00:00,2019,10,31,17
26073,29053,437.5,608.5,32.80,6.10,30.00,69.62,41.22,NaN,87.42,...,2019-10-31 23:00:00,2019,10,31,23,2019-10-31 18:00:00,2019,10,31,18
26074,29054,417.0,576.0,28.95,5.85,26.80,68.35,38.25,NaN,84.80,...,2019-11-01 00:00:00,2019,11,1,0,2019-10-31 19:00:00,2019,10,31,19

In [4]:
delhi.station.unique().size

35

## Get a dataframe for each pollutant in data

In [5]:
# Get a dataframe for each pollutant. Save in a dict of dataframe.

def get_p_df(df,p):
    dfp = df[['station','lat','lon','date_LT','date_UTC','month_LT','month_UTC',"day_LT","hour_LT","day_UTC","hour_UTC",p]]
    return dfp

poll_list= ['pm25', 'o3', 'no', 'no2','nox','rh','temp']  # get only the ones for evalaution ['nox', 'nh3', 'so2', 'temp', 'rh', 'o3','ws', 'bc']
p={}

for sp in poll_list:
    p.update({sp:get_p_df(delhi,sp)})

In [6]:
p['pm25']

,station,lat,lon,date_LT,date_UTC,month_LT,month_UTC,day_LT,hour_LT,day_UTC,hour_UTC,pm25
0,Alipur Delhi - DPCC,28.815329,77.15301,2019-10-01 00:00:00,2019-09-30 19:00:00,10,9,1,0,30,19,54.5
1,Alipur Delhi - DPCC,28.815329,77.15301,2019-10-01 01:00:00,2019-09-30 20:00:00,10,9,1,1,30,20,44.5
2,Alipur Delhi - DPCC,28.815329,77.15301,2019-10-01 02:00:00,2019-09-30 21:00:00,10,9,1,2,30,21,40.5
3,Alipur Delhi - DPCC,28.815329,77.15301,2019-10-01 03:00:00,2019-09-30 22:00:00,10,9,1,3,30,22,43.5
4,Alipur Delhi - DPCC,28.815329,77.15301,2019-10-01 04:00:00,2019-09-30 23:00:00,10,9,1,4,30,23,51.5
...,...,...,...,...,...,...,...,...,...,...,...,...
26070,Vivek Vihar Delhi - DPCC,28.672342,77.31526,2019-10-31 20:00:00,2019-10-31 15:00:00,10,10,31,20,31,15,447.0
26071,Vivek Vihar Delhi - DPCC,28.672342,77.31526,2019-10-31 21:00:00,2019-10-31 16:00:00,10,10,31,21,31,16,446.0
26072,Vivek Vihar Delhi - DPCC,28.672342,77.31526,2019-10-31 22:00:00,2019-10-31 17:00:00,10,10,31,22,31,17,451.5
26073,Vivek Vihar Delhi - DPCC,28.672342,77.31526,2019-10-31 23:00:00,2019-10-31 18:00:00,10,10,31,23,31,18,437.5
26074,Vivek Vihar Delhi - DPCC,28.672342,77.31526,2019-11-01 00:00:00,2019-10-31 19:00:00,11,10,1,0,31,19,417.0

# Cleaning data: steps

## 1) Exlcude NaN, Non valid, negative and zero values

In [7]:
for k,v in p.items():  
    p[k].dropna(inplace=True)  # remove NaN measurements
    p[k].drop(p[k][p[k][k] <=0].index)  # remove negative and zero values

<ipython-input-7-0129f2cd89ca>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  p[k].dropna(inplace=True)  # remove NaN measurements

## 2) Exclude hourly data with  z_score >= 3 respect to daily average and std

In [8]:
# Get daily averages and standard deviation
col_d = ["station","lat", "lon",'month_UTC','day_UTC']
drop_c= ['date_UTC','date_LT','month_LT','day_LT','hour_LT','hour_UTC']
daily_m= {}
daily_std= {}

#mean
for k,v in p.items():
    daily_m.update({k : p[k].drop(drop_c,axis=1).groupby(col_d).mean().reset_index()})
    daily_m[k] = daily_m[k].rename(columns={k: k+ "_dm"})

#std
for k,v in p.items():
    daily_std.update({k : p[k].drop(drop_c,axis=1).groupby(col_d).std().reset_index()})
    daily_std[k] = daily_std[k].rename(columns={k: k+ "_dstd"})

In [9]:
daily_std['pm25']

,station,lat,lon,month_UTC,day_UTC,pm25_dstd
0,Alipur Delhi - DPCC,28.815329,77.15301,9,30,5.856620
1,Alipur Delhi - DPCC,28.815329,77.15301,10,1,10.608630
2,Alipur Delhi - DPCC,28.815329,77.15301,10,2,19.689149
3,Alipur Delhi - DPCC,28.815329,77.15301,10,3,10.696712
4,Alipur Delhi - DPCC,28.815329,77.15301,10,4,4.673981
...,...,...,...,...,...,...
1077,Vivek Vihar Delhi - DPCC,28.672342,77.31526,10,27,246.136102
1078,Vivek Vihar Delhi - DPCC,28.672342,77.31526,10,28,97.722945
1079,Vivek Vihar Delhi - DPCC,28.672342,77.31526,10,29,42.016789
1080,Vivek Vihar Delhi - DPCC,28.672342,77.31526,10,30,47.523850
1081,Vivek Vihar Delhi - DPCC,28.672342,77.31526,10,31,87.561430

In [10]:
#merge all together daily and hourly data
df={}

# merge daily std and mean df.
for k,vm,vd,vh in zip(daily_m.keys(),daily_m.values(),daily_std.values(),p.values()):
    temp=vm.merge(vd, on=col_d)  # merge mean and std  df
    df.update({k:vh.merge(temp, on=col_d)})  # merge with the hourly df

In [11]:
df['pm25'].station.unique()

array(['Alipur  Delhi - DPCC', 'Anand Vihar  Delhi - DPCC',
       'Ashok Vihar  Delhi - DPCC', 'Aya Nagar  Delhi - IMD',
       'Bawana  Delhi - DPCC', 'Burari Crossing  Delhi - IMD',
       'CRRI Mathura Road  Delhi - IMD', 'DTU  Delhi - CPCB',
       'Dr. Karni Singh Shooting Range  Delhi - DPCC',
       'IGI Airport (T3)  Delhi - IMD',
       'IHBAS  Dilshad Garden  Delhi - CPCB', 'ITO  Delhi - CPCB',
       'Jahangirpuri  Delhi - DPCC',
       'Jawaharlal Nehru Stadium  Delhi - DPCC',
       'Lodhi Road  Delhi - IMD',
       'Major Dhyan Chand National Stadium  Delhi - DPCC',
       'Mandir Marg  Delhi - DPCC', 'Mundka  Delhi - DPCC',
       'NSIT Dwarka  Delhi - CPCB', 'Najafgarh  Delhi - DPCC',
       'Narela  Delhi - DPCC', 'Nehru Nagar  Delhi - DPCC',
       'North Campus  DU  Delhi - IMD', 'Okhla Phase-2  Delhi - DPCC',
       'Patparganj  Delhi - DPCC', 'Punjabi Bagh  Delhi - DPCC',
       'Pusa  Delhi - DPCC', 'R K Puram  Delhi - DPCC',
       'Rohini  Delhi - DPCC', 'Shadipur  Delhi - CPCB',
       'Sirifort  Delhi - CPCB', 'Sonia Vihar  Delhi - DPCC',
       'Sri Aurobindo Marg  Delhi - DPCC', 'Vivek Vihar  Delhi - DPCC'],
      dtype=object)

In [12]:
# calculate z scores for each hourly measurement
for k,v in df.items():  
        v["z_"+k]=(v[k] - v[k + "_dm"])/v[k + "_dstd"]

In [13]:
df["pm25"][df["pm25"]["z_pm25"].isna()==True].head()

,station,lat,lon,date_LT,date_UTC,month_LT,month_UTC,day_LT,hour_LT,day_UTC,hour_UTC,pm25,pm25_dm,pm25_dstd,z_pm25
6914,IGI Airport (T3) Delhi - IMD,28.562776,77.118005,2019-10-16 05:00:00,2019-10-16 00:00:00,10,10,16,5,16,0,93.53,93.53,NaN,NaN

Std NaN corespond to days where I have only 1 mesurements. Indeed pandas.std() by default calculates with 1 dof, so divides 
for N-1, not N. These values are going to be eliminated automatically with next step (NaN compared to float is always False).

In [14]:
# Check a min max z
df["pm25"]["z_pm25"].max()

4.4676652395959096

In [15]:
df["pm25"]["z_pm25"].min()

-3.667544668457737

In [16]:
# exclude those with z_score >=3
delhi3={}
for k,v in df.items():  
     delhi3.update({k: v[v["z_"+k].abs() < 3] })

In [17]:
delhi3["pm25"]["z_pm25"].min()

-2.8940812465876844

In [18]:
delhi3["pm25"]["z_pm25"].max()

2.960978676039774

In [19]:
delhi3["pm25"]

,station,lat,lon,date_LT,date_UTC,month_LT,month_UTC,day_LT,hour_LT,day_UTC,hour_UTC,pm25,pm25_dm,pm25_dstd,z_pm25
0,Alipur Delhi - DPCC,28.815329,77.15301,2019-10-01 00:00:00,2019-09-30 19:00:00,10,9,1,0,30,19,54.5,46.900000,5.85662,1.297677
1,Alipur Delhi - DPCC,28.815329,77.15301,2019-10-01 01:00:00,2019-09-30 20:00:00,10,9,1,1,30,20,44.5,46.900000,5.85662,-0.409793
2,Alipur Delhi - DPCC,28.815329,77.15301,2019-10-01 02:00:00,2019-09-30 21:00:00,10,9,1,2,30,21,40.5,46.900000,5.85662,-1.092780
3,Alipur Delhi - DPCC,28.815329,77.15301,2019-10-01 03:00:00,2019-09-30 22:00:00,10,9,1,3,30,22,43.5,46.900000,5.85662,-0.580540
4,Alipur Delhi - DPCC,28.815329,77.15301,2019-10-01 04:00:00,2019-09-30 23:00:00,10,9,1,4,30,23,51.5,46.900000,5.85662,0.785436
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24549,Vivek Vihar Delhi - DPCC,28.672342,77.31526,2019-10-31 20:00:00,2019-10-31 15:00:00,10,10,31,20,31,15,447.0,387.805556,87.56143,0.676033
24550,Vivek Vihar Delhi - DPCC,28.672342,77.31526,2019-10-31 21:00:00,2019-10-31 16:00:00,10,10,31,21,31,16,446.0,387.805556,87.56143,0.664613
24551,Vivek Vihar Delhi - DPCC,28.672342,77.31526,2019-10-31 22:00:00,2019-10-31 17:00:00,10,10,31,22,31,17,451.5,387.805556,87.56143,0.727426
24552,Vivek Vihar Delhi - DPCC,28.672342,77.31526,2019-10-31 23:00:00,2019-10-31 18:00:00,10,10,31,23,31,18,437.5,387.805556,87.56143,0.567538
24553,Vivek Vihar Delhi - DPCC,28.672342,77.31526,2019-11-01 00:00:00,2019-10-31 19:00:00,11,10,1,0,31,19,417.0,387.805556,87.56143,0.333417

## 3) Exclude days with less then 12 hourly measurement per day

In [20]:
delhi4={}
for k,v in delhi3.items():
    #Count how many hourly measurements per day I have.
    temp = v.drop(drop_c,axis=1).groupby(col_d)[k].count().reset_index()
    temp.rename(columns={k: "num_hour"},inplace=True)
    delhi4.update({k: v.merge(temp, on=(col_d))}) 
    
    #drop measurements that have less that 12 hourly data per day.
    delhi4[k]= delhi4[k][delhi4[k]["num_hour"]>=12]

In [21]:
delhi4['pm25']

,station,lat,lon,date_LT,date_UTC,month_LT,month_UTC,day_LT,hour_LT,day_UTC,hour_UTC,pm25,pm25_dm,pm25_dstd,z_pm25,num_hour
5,Alipur Delhi - DPCC,28.815329,77.15301,2019-10-01 05:00:00,2019-10-01 00:00:00,10,10,1,5,1,0,56.0,36.770833,10.60863,1.812597,24
6,Alipur Delhi - DPCC,28.815329,77.15301,2019-10-01 06:00:00,2019-10-01 01:00:00,10,10,1,6,1,1,53.0,36.770833,10.60863,1.529808,24
7,Alipur Delhi - DPCC,28.815329,77.15301,2019-10-01 07:00:00,2019-10-01 02:00:00,10,10,1,7,1,2,51.0,36.770833,10.60863,1.341282,24
8,Alipur Delhi - DPCC,28.815329,77.15301,2019-10-01 08:00:00,2019-10-01 03:00:00,10,10,1,8,1,3,55.5,36.770833,10.60863,1.765465,24
9,Alipur Delhi - DPCC,28.815329,77.15301,2019-10-01 09:00:00,2019-10-01 04:00:00,10,10,1,9,1,4,44.0,36.770833,10.60863,0.681442,24
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24519,Vivek Vihar Delhi - DPCC,28.672342,77.31526,2019-10-31 20:00:00,2019-10-31 15:00:00,10,10,31,20,31,15,447.0,387.805556,87.56143,0.676033,18
24520,Vivek Vihar Delhi - DPCC,28.672342,77.31526,2019-10-31 21:00:00,2019-10-31 16:00:00,10,10,31,21,31,16,446.0,387.805556,87.56143,0.664613,18
24521,Vivek Vihar Delhi - DPCC,28.672342,77.31526,2019-10-31 22:00:00,2019-10-31 17:00:00,10,10,31,22,31,17,451.5,387.805556,87.56143,0.727426,18
24522,Vivek Vihar Delhi - DPCC,28.672342,77.31526,2019-10-31 23:00:00,2019-10-31 18:00:00,10,10,31,23,31,18,437.5,387.805556,87.56143,0.567538,18
24523,Vivek Vihar Delhi - DPCC,28.672342,77.31526,2019-11-01 00:00:00,2019-10-31 19:00:00,11,10,1,0,31,19,417.0,387.805556,87.56143,0.333417,18

In [22]:
delhi4["pm25"].num_hour.max()

24

## 4) Exclude stations with less than 90% of days per simulation period (~1 month)

In [23]:
#replace month with season column based on month value
maps = {1: "winter", 4:"premonsoon", 7:"monsoon",9:"postmonsoon", 10:"postmonsoon"}

for k,v in delhi4.items():
    v["season"]=v["month_UTC"]
    v.replace({"season": maps},inplace=True)

In [24]:
delhi4["pm25"].month_UTC.unique()

array([10])

In [25]:
delhi4["pm25"].head()

,station,lat,lon,date_LT,date_UTC,month_LT,month_UTC,day_LT,hour_LT,day_UTC,hour_UTC,pm25,pm25_dm,pm25_dstd,z_pm25,num_hour,season
5,Alipur Delhi - DPCC,28.815329,77.15301,2019-10-01 05:00:00,2019-10-01 00:00:00,10,10,1,5,1,0,56.0,36.770833,10.60863,1.812597,24,postmonsoon
6,Alipur Delhi - DPCC,28.815329,77.15301,2019-10-01 06:00:00,2019-10-01 01:00:00,10,10,1,6,1,1,53.0,36.770833,10.60863,1.529808,24,postmonsoon
7,Alipur Delhi - DPCC,28.815329,77.15301,2019-10-01 07:00:00,2019-10-01 02:00:00,10,10,1,7,1,2,51.0,36.770833,10.60863,1.341282,24,postmonsoon
8,Alipur Delhi - DPCC,28.815329,77.15301,2019-10-01 08:00:00,2019-10-01 03:00:00,10,10,1,8,1,3,55.5,36.770833,10.60863,1.765465,24,postmonsoon
9,Alipur Delhi - DPCC,28.815329,77.15301,2019-10-01 09:00:00,2019-10-01 04:00:00,10,10,1,9,1,4,44.0,36.770833,10.60863,0.681442,24,postmonsoon

In [26]:
# Drop unuseful columns
for k,v in delhi4.items():
    delhi4[k]=delhi4[k].drop(columns=["z_"+k, "num_hour"])

In [27]:
delhi4["pm25"]

,station,lat,lon,date_LT,date_UTC,month_LT,month_UTC,day_LT,hour_LT,day_UTC,hour_UTC,pm25,pm25_dm,pm25_dstd,season
5,Alipur Delhi - DPCC,28.815329,77.15301,2019-10-01 05:00:00,2019-10-01 00:00:00,10,10,1,5,1,0,56.0,36.770833,10.60863,postmonsoon
6,Alipur Delhi - DPCC,28.815329,77.15301,2019-10-01 06:00:00,2019-10-01 01:00:00,10,10,1,6,1,1,53.0,36.770833,10.60863,postmonsoon
7,Alipur Delhi - DPCC,28.815329,77.15301,2019-10-01 07:00:00,2019-10-01 02:00:00,10,10,1,7,1,2,51.0,36.770833,10.60863,postmonsoon
8,Alipur Delhi - DPCC,28.815329,77.15301,2019-10-01 08:00:00,2019-10-01 03:00:00,10,10,1,8,1,3,55.5,36.770833,10.60863,postmonsoon
9,Alipur Delhi - DPCC,28.815329,77.15301,2019-10-01 09:00:00,2019-10-01 04:00:00,10,10,1,9,1,4,44.0,36.770833,10.60863,postmonsoon
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24519,Vivek Vihar Delhi - DPCC,28.672342,77.31526,2019-10-31 20:00:00,2019-10-31 15:00:00,10,10,31,20,31,15,447.0,387.805556,87.56143,postmonsoon
24520,Vivek Vihar Delhi - DPCC,28.672342,77.31526,2019-10-31 21:00:00,2019-10-31 16:00:00,10,10,31,21,31,16,446.0,387.805556,87.56143,postmonsoon
24521,Vivek Vihar Delhi - DPCC,28.672342,77.31526,2019-10-31 22:00:00,2019-10-31 17:00:00,10,10,31,22,31,17,451.5,387.805556,87.56143,postmonsoon
24522,Vivek Vihar Delhi - DPCC,28.672342,77.31526,2019-10-31 23:00:00,2019-10-31 18:00:00,10,10,31,23,31,18,437.5,387.805556,87.56143,postmonsoon
24523,Vivek Vihar Delhi - DPCC,28.672342,77.31526,2019-11-01 00:00:00,2019-10-31 19:00:00,11,10,1,0,31,19,417.0,387.805556,87.56143,postmonsoon

In [28]:
col_s =["station","lat", "lon",'season','month_UTC','day_UTC']
col_d=["station","lat", "lon",'season','month_UTC']
delhi5={}

drop_c= ['date_UTC','date_LT','month_LT','day_LT','hour_LT','hour_UTC']

for k,v in delhi4.items():
    #Count how many daily measurements per season I have.
    
    temp=(v.drop(drop_c, axis=1).groupby(col_s).mean().reset_index()) #get daily mean.
    temp2=temp.groupby(col_d)['day_UTC'].count().reset_index()
    temp2.rename(columns={'day_UTC': "num_days"},inplace=True)
    delhi5.update({k: v.merge(temp2, on=(col_d))}) 
    
    #drop measurements that dont have at least 90% of days per simulation period. (in this case: 28/31 days)
    delhi5[k]= delhi5[k][delhi5[k]["num_days"]>=28]

In [29]:
#check number of station per pollutant
for k in delhi5.keys():
    print(k,delhi5[k].station.unique().size)

pm25 33
o3 31
no 34
no2 34
nox 34
rh 28
temp 6

In [30]:
#check min max days
delhi5["pm25"].num_days.max()

31

In [31]:
delhi5["pm25"].num_days.min()

28

In [32]:
# Drop unuseful columns
for k,v in delhi5.items():
    delhi5[k]=delhi5[k].drop(columns=[k+"_dm",k+"_dstd",'num_days'])

In [33]:
delhi5["pm25"]

,station,lat,lon,date_LT,date_UTC,month_LT,month_UTC,day_LT,hour_LT,day_UTC,hour_UTC,pm25,season
0,Alipur Delhi - DPCC,28.815329,77.15301,2019-10-01 05:00:00,2019-10-01 00:00:00,10,10,1,5,1,0,56.0,postmonsoon
1,Alipur Delhi - DPCC,28.815329,77.15301,2019-10-01 06:00:00,2019-10-01 01:00:00,10,10,1,6,1,1,53.0,postmonsoon
2,Alipur Delhi - DPCC,28.815329,77.15301,2019-10-01 07:00:00,2019-10-01 02:00:00,10,10,1,7,1,2,51.0,postmonsoon
3,Alipur Delhi - DPCC,28.815329,77.15301,2019-10-01 08:00:00,2019-10-01 03:00:00,10,10,1,8,1,3,55.5,postmonsoon
4,Alipur Delhi - DPCC,28.815329,77.15301,2019-10-01 09:00:00,2019-10-01 04:00:00,10,10,1,9,1,4,44.0,postmonsoon
...,...,...,...,...,...,...,...,...,...,...,...,...,...
24259,Vivek Vihar Delhi - DPCC,28.672342,77.31526,2019-10-31 20:00:00,2019-10-31 15:00:00,10,10,31,20,31,15,447.0,postmonsoon
24260,Vivek Vihar Delhi - DPCC,28.672342,77.31526,2019-10-31 21:00:00,2019-10-31 16:00:00,10,10,31,21,31,16,446.0,postmonsoon
24261,Vivek Vihar Delhi - DPCC,28.672342,77.31526,2019-10-31 22:00:00,2019-10-31 17:00:00,10,10,31,22,31,17,451.5,postmonsoon
24262,Vivek Vihar Delhi - DPCC,28.672342,77.31526,2019-10-31 23:00:00,2019-10-31 18:00:00,10,10,31,23,31,18,437.5,postmonsoon
24263,Vivek Vihar Delhi - DPCC,28.672342,77.31526,2019-11-01 00:00:00,2019-10-31 19:00:00,11,10,1,0,31,19,417.0,postmonsoon

## Get list of stations

In [34]:
list(delhi5.keys())

['pm25', 'o3', 'no', 'no2', 'nox', 'rh', 'temp']

In [35]:
#get list of all stations
col_st = ["station","lat","lon"]
pol=list(delhi5.keys())

stations = pd.DataFrame(columns=col_st+pol)

for k,v in delhi5.items():
    temp=delhi5[k][col_st]
    stations= stations.append(temp)

In [36]:
stations

,station,lat,lon,pm25,o3,no,no2,nox,rh,temp
0,Alipur Delhi - DPCC,28.815329,77.153010,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Alipur Delhi - DPCC,28.815329,77.153010,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Alipur Delhi - DPCC,28.815329,77.153010,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Alipur Delhi - DPCC,28.815329,77.153010,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Alipur Delhi - DPCC,28.815329,77.153010,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
4381,Sirifort Delhi - CPCB,28.550425,77.215938,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4382,Sirifort Delhi - CPCB,28.550425,77.215938,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4383,Sirifort Delhi - CPCB,28.550425,77.215938,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4384,Sirifort Delhi - CPCB,28.550425,77.215938,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4385,Sirifort Delhi - CPCB,28.550425,77.215938,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [37]:
stations = stations.drop_duplicates().reset_index(drop=True)  # drop same raws

In [38]:
stations.sort_values("station").reset_index(drop=True)

,station,lat,lon,pm25,o3,no,no2,nox,rh,temp
0,Alipur Delhi - DPCC,28.815329,77.153010,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Anand Vihar Delhi - DPCC,28.646835,77.316032,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Ashok Vihar Delhi - DPCC,28.695381,77.181665,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Aya Nagar Delhi - IMD,28.470691,77.109936,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Bawana Delhi - DPCC,28.776200,77.051074,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,Burari Crossing Delhi - IMD,28.725650,77.201157,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,CRRI Mathura Road Delhi - IMD,28.551201,77.273574,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,DTU Delhi - CPCB,28.750050,77.111261,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,Dr. Karni Singh Shooting Range Delhi - DPCC,28.498571,77.264840,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,East Arjun Nagar Delhi - CPCB,28.655602,77.285932,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,IGI Airport (T3) Delhi - IMD,28.562776,77.118005,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,IHBAS Dilshad Garden Delhi - CPCB,28.681174,77.302523,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,ITO Delhi - CPCB,28.631694,77.249439,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,Jahangirpuri Delhi - DPCC,28.732820,77.170633,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,Jawaharlal Nehru Stadium Delhi - DPCC,28.580280,77.233829,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,Lodhi Road Delhi - IMD,28.591825,77.227307,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,Major Dhyan Chand National Stadium Delhi - DPCC,28.611281,77.237738,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,Mandir Marg Delhi - DPCC,28.636429,77.201067,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,Mundka Delhi - DPCC,28.684678,77.076574,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,NSIT Dwarka Delhi - CPCB,28.609090,77.032541,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,Najafgarh Delhi - DPCC,28.570173,76.933762,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,Narela Delhi - DPCC,28.822836,77.101981,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,Nehru Nagar Delhi - DPCC,28.567890,77.250515,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,North Campus DU Delhi - IMD,28.657381,77.158545,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,Okhla Phase-2 Delhi - DPCC,28.530785,77.271255,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,Patparganj Delhi - DPCC,28.623748,77.287205,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,Punjabi Bagh Delhi - DPCC,28.674045,77.131023,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,Pusa Delhi - DPCC,28.639645,77.146262,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,R K Puram Delhi - DPCC,28.563262,77.186937,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,Rohini Delhi - DPCC,28.732528,77.119920,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,Shadipur Delhi - CPCB,28.651478,77.147311,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31,Sirifort Delhi - CPCB,28.550425,77.215938,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32,Sonia Vihar Delhi - DPCC,28.710508,77.249485,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,Sri Aurobindo Marg Delhi - DPCC,28.531346,77.190156,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,Vivek Vihar Delhi - DPCC,28.672342,77.315260,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## Drop duplicate stations

In [39]:
#drop stations with same lat lon but htat have different names (spelling erros, if any): unique Station is identified by la lon.
stations= stations.drop_duplicates(subset=['lat', 'lon']).sort_values("station").reset_index(drop=True)

In [40]:
stations

,station,lat,lon,pm25,o3,no,no2,nox,rh,temp
0,Alipur Delhi - DPCC,28.815329,77.153010,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Anand Vihar Delhi - DPCC,28.646835,77.316032,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Ashok Vihar Delhi - DPCC,28.695381,77.181665,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Aya Nagar Delhi - IMD,28.470691,77.109936,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Bawana Delhi - DPCC,28.776200,77.051074,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,Burari Crossing Delhi - IMD,28.725650,77.201157,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,CRRI Mathura Road Delhi - IMD,28.551201,77.273574,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,DTU Delhi - CPCB,28.750050,77.111261,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,Dr. Karni Singh Shooting Range Delhi - DPCC,28.498571,77.264840,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,East Arjun Nagar Delhi - CPCB,28.655602,77.285932,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,IGI Airport (T3) Delhi - IMD,28.562776,77.118005,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,IHBAS Dilshad Garden Delhi - CPCB,28.681174,77.302523,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,ITO Delhi - CPCB,28.631694,77.249439,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,Jahangirpuri Delhi - DPCC,28.732820,77.170633,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,Jawaharlal Nehru Stadium Delhi - DPCC,28.580280,77.233829,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,Lodhi Road Delhi - IMD,28.591825,77.227307,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,Major Dhyan Chand National Stadium Delhi - DPCC,28.611281,77.237738,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,Mandir Marg Delhi - DPCC,28.636429,77.201067,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,Mundka Delhi - DPCC,28.684678,77.076574,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,NSIT Dwarka Delhi - CPCB,28.609090,77.032541,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,Najafgarh Delhi - DPCC,28.570173,76.933762,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,Narela Delhi - DPCC,28.822836,77.101981,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,Nehru Nagar Delhi - DPCC,28.567890,77.250515,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,North Campus DU Delhi - IMD,28.657381,77.158545,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,Okhla Phase-2 Delhi - DPCC,28.530785,77.271255,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,Patparganj Delhi - DPCC,28.623748,77.287205,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,Punjabi Bagh Delhi - DPCC,28.674045,77.131023,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,Pusa Delhi - DPCC,28.639645,77.146262,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,R K Puram Delhi - DPCC,28.563262,77.186937,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,Rohini Delhi - DPCC,28.732528,77.119920,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,Shadipur Delhi - CPCB,28.651478,77.147311,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31,Sirifort Delhi - CPCB,28.550425,77.215938,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32,Sonia Vihar Delhi - DPCC,28.710508,77.249485,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,Sri Aurobindo Marg Delhi - DPCC,28.531346,77.190156,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,Vivek Vihar Delhi - DPCC,28.672342,77.315260,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## Which station measures what?

In [41]:
#List of all stations
st_list = stations.station.unique()

# Check with loop which station are in each pollutant df
for sname,i in zip(st_list, np.arange(0, len(st_list))):
    for k,v in delhi5.items():
        if sname in v.station.unique():
            stations[k][i]='x'
        else:
            stations[k][i]=''

<ipython-input-41-1f518d4344ad>:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  stations[k][i]='x'
<ipython-input-41-1f518d4344ad>:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  stations[k][i]=''

In [42]:
stations

,station,lat,lon,pm25,o3,no,no2,nox,rh,temp
0,Alipur Delhi - DPCC,28.815329,77.153010,x,,x,x,x,x,
1,Anand Vihar Delhi - DPCC,28.646835,77.316032,x,x,x,x,x,x,
2,Ashok Vihar Delhi - DPCC,28.695381,77.181665,x,x,x,x,x,x,
3,Aya Nagar Delhi - IMD,28.470691,77.109936,x,x,x,x,x,,
4,Bawana Delhi - DPCC,28.776200,77.051074,x,x,x,x,x,x,
5,Burari Crossing Delhi - IMD,28.725650,77.201157,x,x,x,x,x,,
6,CRRI Mathura Road Delhi - IMD,28.551201,77.273574,x,x,x,x,x,,
7,DTU Delhi - CPCB,28.750050,77.111261,x,x,x,x,x,x,x
8,Dr. Karni Singh Shooting Range Delhi - DPCC,28.498571,77.264840,x,,x,x,x,x,
9,East Arjun Nagar Delhi - CPCB,28.655602,77.285932,,,,,,x,x
10,IGI Airport (T3) Delhi - IMD,28.562776,77.118005,x,x,x,x,x,,
11,IHBAS Dilshad Garden Delhi - CPCB,28.681174,77.302523,x,,x,x,x,x,x
12,ITO Delhi - CPCB,28.631694,77.249439,x,x,x,x,x,,
13,Jahangirpuri Delhi - DPCC,28.732820,77.170633,x,x,x,x,x,x,
14,Jawaharlal Nehru Stadium Delhi - DPCC,28.580280,77.233829,x,x,x,x,x,x,
15,Lodhi Road Delhi - IMD,28.591825,77.227307,x,x,x,x,x,,
16,Major Dhyan Chand National Stadium Delhi - DPCC,28.611281,77.237738,x,x,x,x,x,x,
17,Mandir Marg Delhi - DPCC,28.636429,77.201067,x,x,x,x,x,x,
18,Mundka Delhi - DPCC,28.684678,77.076574,x,x,x,x,x,x,
19,NSIT Dwarka Delhi - CPCB,28.609090,77.032541,x,x,x,x,x,x,x
20,Najafgarh Delhi - DPCC,28.570173,76.933762,x,x,x,x,x,x,
21,Narela Delhi - DPCC,28.822836,77.101981,x,x,x,x,x,x,
22,Nehru Nagar Delhi - DPCC,28.567890,77.250515,x,x,x,x,x,x,
23,North Campus DU Delhi - IMD,28.657381,77.158545,x,x,x,x,x,,
24,Okhla Phase-2 Delhi - DPCC,28.530785,77.271255,x,x,x,x,x,x,
25,Patparganj Delhi - DPCC,28.623748,77.287205,x,x,x,x,x,x,
26,Punjabi Bagh Delhi - DPCC,28.674045,77.131023,x,x,x,x,x,x,
27,Pusa Delhi - DPCC,28.639645,77.146262,x,x,x,x,x,x,
28,R K Puram Delhi - DPCC,28.563262,77.186937,,x,x,x,x,x,
29,Rohini Delhi - DPCC,28.732528,77.119920,x,x,x,x,x,x,
30,Shadipur Delhi - CPCB,28.651478,77.147311,x,x,x,x,x,x,x
31,Sirifort Delhi - CPCB,28.550425,77.215938,x,x,x,x,x,x,x
32,Sonia Vihar Delhi - DPCC,28.710508,77.249485,x,x,x,x,x,x,
33,Sri Aurobindo Marg Delhi - DPCC,28.531346,77.190156,x,x,x,x,x,x,
34,Vivek Vihar Delhi - DPCC,28.672342,77.315260,x,x,x,x,x,x,

## Save all data to a file

In [43]:
#save as a single dataframe

In [44]:
# create unique dataframe with all data
data = delhi5['pm25'].drop('pm25',axis=True)

cols=data.columns.tolist()

for k in pol:
    temp=delhi5[k]
    data= pd.merge(data,temp, on=cols,how='outer')

In [45]:
data.station.unique().size

35

In [46]:
with pd.ExcelWriter('./cpcb_oct2019_cleaned.xlsx') as writer:
            data.to_excel(writer, sheet_name='data')

# Add station list as separate sheet
stations.to_excel(writer, sheet_name="stations")          
writer.save()